### PR TITLE
change title on README

### PR DESCRIPTION
**Pull request by AbhishekGMZ**

### CODE REVIEW

**Review by AbhishekGMZ — COMMENTED** [review]
Test

**Review by SvermaMZ — APPROVED** [review]
Approve for tettris

**Comment by SvermaMZ** [comment]
it looks good to me

**Review by SvermaMZ — APPROVED** [review]
good

**Review by SvermaMZ — APPROVED** [review]

**Review by SvermaMZ — APPROVED** [review]

**Comment by AbhishekGMZ** [comment]
done

**Pull request merged**
